import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { CollaborativeApp } from "@/app/CollaborativeApp";
import { Room } from "@/app/Room";
import { cn } from "@/lib/utils";
import UIWrapper from "@/components/ui/wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "scrollbar h-full scroll-smooth antialiased ",
        ` ${GeistSans.className}`
      )}
    >
      <body className=" h-full">
        <ThemeProvider attribute="class" defaultTheme="dark">
          <TooltipProvider delayDuration={300}>
            <UIWrapper>{children}</UIWrapper>
          </TooltipProvider>
        </ThemeProvider>
        {/* <ProgressBar />
      <Nav /> */}
        <Toaster />
      </body>
    </html>
  );
}
